### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by assembleDebug** [j-hc/mindetach-magisk#1]
It doesn't seems to work for me. I am using your YouTube revanced module  along with your Mindetach module. But YouTube is showing up in the Updates section on play store. I tried clearing play store data but it didn't help. 

Running MIUI 13.0.4 based on Android 12 on Redmi note 10 Pro.

**Comment by j-hc** [comment]
I am aware of the issue. A new version is being tested in https://t.me/rvc_magisk

**Comment by j-hc** [comment]
you can try the new version: https://github.com/j-hc/mindetach-magisk/releases/tag/20220812

**Comment by assembleDebug** [comment]
It worked, thanks 👍.
