### ISSUE TITLE
Play Store crashing on Google Pixel

### ISSUE THREAD

**Issue by apernouille** [j-hc/mindetach-magisk#10]
Hello,
The mindetach app crashes the Play Store on my Pixel 3 XL.
The Play Store crashes within seconds of opening it and even when I'm outside the app.
I use mindetach for YouTube

**Versions :**
Android 12
Magisk : 25.2
Mindetach: v3.3
YouTube ReVanced : v18.05.40
PlayStore : 35.0.15-21 [0] [PR] 519197268

I don't know what additional information to give. Let me know if you want specific information.

Thanks in advance for your help

**Comment by j-hc** [comment]
can you share logs

**Comment by apernouille** [comment]
I already cleared play store data and reflashed v3.3 multiple times.

Here's `adb logcat | grep vending` when opening Play Store

If you need other logs ask me

_Note : There are Pixelify logs but the problem was exactly the same before I installed it so it must not come from there._

> com.android.vending/com.google.android.finsky.scheduler.process.mainimpl.PhoneskyJobServiceMain` in 1000ms for connection
> 04-25 23:22:11.687  1981  3958 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.android.vending/.AssetBrowserActivity bnds=[586,2348][855,2561]} from uid 10191
> 04-25 23:22:11.705  1981  2101 I ActivityManager: com.android.vending is exempt from freezer
> 04-25 23:22:11.717  1981  2116 I ActivityManager: Start proc 16178:com.android.vending/u0a120 for pre-top-activity {com.android.vending/com.android.vending.AssetBrowserActivity}
> 04-25 23:22:11.763 16178 16178 I Pixelify: inject android.os.Build for com.android.vending with 
> 04-25 23:22:11.836 16178 16178 D nativeloader: Configuring classloader-namespace for other apk /system/framework/org.apache.http.legacy.jar. target_sdk_version=33, uses_libraries=ALL, library_path=/data/app/~~uJsjYuFHcNlZl7glYoLV4w==/com.android.vending-mO3aCSuvYL0JDp4dk4MOdg==/lib/arm64:/data/app/~~uJsjYuFHcNlZl7glYoLV4w==/com.android.vending-mO3aCSuvYL0JDp4dk4MOdg==/base.apk!/lib/arm64-v8a:/data/app/~~uJsjYuFHcNlZl7glYoLV4w==/com.android.vending-mO3aCSuvYL0JDp4dk4MOdg==/split_config.arm64_v8a.apk!/lib/arm64-v8a:/data/app/~~uJsjYuFHcNlZl7glYoLV4w==/com.android.vending-mO3aCSuvYL0JDp4dk4MOdg==/split_config.en.apk!/lib/arm64-v8a:/data/app/~~uJsjYuFHcNlZl7glYoLV4w==/com.android.vending-mO3aCSuvYL0JDp4dk4MOdg==/split_config.fr.apk!/lib/arm64-v8a:/data/app/~~uJsjYuFHcNlZl7glYoLV4w==/com.android.vending-mO3aCSuvYL0JDp4dk4MOdg==/split_phonesky_data_loader.apk!/lib/arm64-v8a:/data/app/~~uJsjYuFHcNlZl7glYoLV4w==/com.android.vending-mO3aCSuvYL0JDp4dk4MOdg==/split_phonesky_data_loader.config.arm64_v8a.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user
> 04-25 23:22:11.840 16178 16178 W ziparchive: Unable to open '/data/app/~~uJsjYuFHcNlZl7glYoLV4w==/com.android.vending-mO3aCSuvYL0JDp4dk4MOdg==/split_config.arm64_v8a.dm': No such file or directory
> 04-25 23:22:11.840 16178 16178 W ziparchive: Unable to open '/data/app/~~uJsjYuFHcNlZl7glYoLV4w==/com.android.vending-mO3aCSuvYL0JDp4dk4MOdg==/split_config.arm64_v8a.dm': No such file or directory
> 04-25 23:22:11.841 16178 16178 W ziparchive: Unable to open '/data/app/~~uJsjYuFHcNlZl7glYoLV4w==/com.android.vending-mO3aCSuvYL0JDp4dk4MOdg==/split_config.en.dm': No such file or directory
> 04-25 23:22:11.841 16178 16178 W ziparchive: Unable to open '/data/app/~~uJsjYuFHcNlZl7glYoLV4w==/com.android.vending-mO3aCSuvYL0JDp4dk4MOdg==/split_config.en.dm': No such file or directory
> 04-25 23:22:11.841 16178 16178 W ziparchive: Unable to open '/data/app/~~uJsjYuFHcNlZl7glYoLV4w==/com.android.vending-mO3aCSuvYL0JDp4dk4MOdg==/split_config.fr.dm': No such file or directory
> 04-25 23:22:11.841 16178 16178 W ziparchive: Unable to open '/data/app/~~uJsjYuFHcNlZl7glYoLV4w==/com.android.vending-mO3aCSuvYL0JDp4dk4MOdg==/split_config.fr.dm': No such file or directory
> 04-25 23:22:11.841 16178 16178 W ziparchive: Unable to open '/data/app/~~uJsjYuFHcNlZl7glYoLV4w==/com.android.vending-mO3aCSuvYL0JDp4dk4MOdg==/split_phonesky_data_loader.dm': No such file or directory
> 04-25 23:22:11.841 16178 16178 W ziparchive: Unable to open '/data/app/~~uJsjYuFHcNlZl7glYoLV4w==/com.android.vending-mO3aCSuvYL0JDp4dk4MOdg==/split_phonesky_data_loader.dm': No such file or directory
> 04-25 23:22:11.841 16178 16178 W ziparchive: Unable to open '/data/app/~~uJsjYuFHcNlZl7glYoLV4w==/com.android.vending-mO3aCSuvYL0JDp4dk4MOdg==/split_phonesky_data_loader.config.arm64_v8a.dm': No such file or directory
> 04-25 23:22:11.841 16178 16178 W ziparchive: Unable to open '/data/app/~~uJsjYuFHcNlZl7glYoLV4w==/com.android.vending-mO3aCSuvYL0JDp4dk4MOdg==/split_phonesky_data_loader.config.arm64_v8a.dm': No such file or directory
> 04-25 23:22:11.843 16178 16178 D nativeloader: Configuring classloader-namespace for other apk /data/app/~~uJsjYuFHcNlZl7glYoLV4w==/com.android.vending-mO3aCSuvYL0JDp4dk4MOdg==/base.apk:/data/app/~~uJsjYuFHcNlZl7glYoLV4w==/com.android.vending-mO3aCSuvYL0JDp4dk4MOdg==/split_config.arm64_v8a.apk:/data/app/~~uJsjYuFHcNlZl7glYoLV4w==/com.android.vending-mO3aCSuvYL0JDp4dk4MOdg==/split_config.en.apk:/data/app/~~uJsjYuFHcNlZl7glYoLV4w==/com.android.vending-mO3aCSuvYL0JDp4dk4MOdg==/split_config.fr.apk:/data/app/~~uJsjYuFHcNlZl7glYoLV4w==/com.android.vending-mO3aCSuvYL0JDp4dk4MOdg==/split_phonesky_data_loader.apk:/data/app/~~uJsjYuFHcNlZl7glYoLV4w==/com.android.vending-mO3aCSuvYL0JDp4dk4MOdg==/split_phonesky_data_loader.config.arm64_v8a.apk. target_sdk_version=33, uses_libraries=, library_path=/data/app/~~uJsjYuFHcNlZl7glYoLV4w==/com.android.vending-mO3aCSuvYL0JDp4dk4MOdg==/lib/arm64:/data/app/~~uJsjYuFHcNlZl7glYoLV4w==/com.android.vending-mO3aCSuvYL0JDp4dk4MOdg==/base.apk!/lib/arm64-v8a:/data/app/~~uJsjYuFHcNlZl7glYoLV4w==/com.android.vending-mO3aCSuvYL0JDp4dk4M
> 04-25 23:22:11.850 16178 16178 V GraphicsEnvironment: ANGLE Developer option for 'com.android.vending' set to: 'default'
> 04-25 23:22:12.014  1981  3965 D ConnectivityService: requestNetwork for uid/pid:10120/16178 activeRequest: null callbackRequest: 2884 [NetworkRequest [ REQUEST id=2885, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10120 RequestorUid: 10120 RequestorPkg: com.android.vending UnderlyingNetworks: Null] ]] callback flags: 0 order: 2147483647
> 04-25 23:22:12.018  1981  2529 D WifiNetworkFactory: got request NetworkRequest [ REQUEST id=2885, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10120 RequestorUid: 10120 RequestorPkg: com.android.vending UnderlyingNetworks: Null] ]
> 04-25 23:22:12.018  1981  2529 D UntrustedWifiNetworkFactory: got request NetworkRequest [ REQUEST id=2885, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10120 RequestorUid: 10120 RequestorPkg: com.android.vending UnderlyingNetworks: Null] ]
> 04-25 23:22:12.018  1981  2529 D OemPaidWifiNetworkFactory: got request NetworkRequest [ REQUEST id=2885, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10120 RequestorUid: 10120 RequestorPkg: com.android.vending UnderlyingNetworks: Null] ]
> 04-25 23:22:12.018  1981  2529 D MultiInternetWifiNetworkFactory: got request NetworkRequest [ REQUEST id=2885, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10120 RequestorUid: 10120 RequestorPkg: com.android.vending UnderlyingNetworks: Null] ]
> 04-25 23:22:12.021 16178 16220 I Finsky  : [59] rfp.run(35): SysCUA: Set {com.android.vending/com.google.android.finsky.systemcomponentupdateui.common.SystemComponentUpdateActivity} enabled state to 1
> 04-25 23:22:12.253  3154  6471 I FacsCacheGmsModule: Receiving API connection to FACS API from package 'com.android.vending'...
> 04-25 23:22:12.271  3154  4860 I FacsCacheGmsModule: Received 'getActivityControlsSettings' request from package 'com.android.vending', instance id 'common', version '1'...
> 04-25 23:22:12.306  1981  2097 I ActivityTaskManager: Displayed com.android.vending/.AssetBrowserActivity: +608ms
> 04-25 23:22:12.319  3250  3328 I MdiSyncModule: Receiving API connection from package 'com.android.vending'...
> 04-25 23:22:12.329  3250  3940 I MdiSyncModule: Receiving API connection from package 'com.android.vending'...
> 04-25 23:22:12.394  4720  4720 I GoogleInputMethodService: GoogleInputMethodService.onStartInput():1917 onStartInput(EditorInfo{inputType=0x0(NULL) imeOptions=0x0 privateImeOptions=null actionName=UNSPECIFIED actionLabel=null actionId=0 initialSelStart=-1 initialSelEnd=-1 initialCapsMode=0x0 hintText=null label=null packageName=com.android.vending fieldId=-1 fieldName=null extras=null hintLocales=[]}, false)
> 04-25 23:22:12.655  1981  3965 W InputManager-JNI: Input channel object 'f9025fe Splash Screen com.android.vending (client)' was disposed without first being removed with the input manager!
> 04-25 23:22:12.857  1981  2097 I ActivityTaskManager: Fully drawn com.android.vending/.AssetBrowserActivity: +1s169ms
> 04-25 23:22:14.856  1981  2840 W ActivityTaskManager:   Force finishing activity com.android.vending/.AssetBrowserActivity
> 04-25 23:22:14.955  1981  7431 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(uid/pid:10120/16178, [NetworkRequest [ LISTEN id=2886, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10120 RequestorUid: 10120 RequestorPkg: com.android.vending UnderlyingNetworks: Null] ]], android.os.BinderProxy@dae0b81)
> 04-25 23:22:14.955  1981  7445 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(uid/pid:10120/16178, [NetworkRequest [ REQUEST id=2885, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10120 RequestorUid: 10120 RequestorPkg: com.android.vending UnderlyingNetworks: Null] ]], android.os.BinderProxy@1626426)
> 04-25 23:22:14.955  1981  7443 I ActivityManager: Process com.android.vending (pid 16178) has died: fg  TOP 
> 04-25 23:22:14.956  1981  2550 D ConnectivityService: releasing NetworkRequest [ REQUEST id=2885, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10120 RequestorUid: 10120 RequestorPkg: com.android.vending UnderlyingNetworks: Null] ] (release request)
> 04-25 23:22:14.956  1981  7431 I WindowManager: WIN DEATH: Window{68e0e1d u0 com.android.vending/com.android.vending.AssetBrowserActivity}
> 04-25 23:22:14.957  1981  7431 W InputManager-JNI: Input channel object '68e0e1d com.android.vending/com.android.vending.AssetBrowserActivity (client)' was disposed without first being removed with the input manager!
> 04-25 23:22:14.962  1981  7443 W ActivityManager: Scheduling restart of crashed service com.android.vending/com.google.android.finsky.scheduler.process.mainimpl.PhoneskyJobServiceMain in 1000ms for connection
> 04-25 23:22:15.358  1981  2101 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{2a6a380 u0 com.android.vending/.AssetBrowserActivity t-1 f}}

**Comment by j-hc** [comment]
this dont include the crash logs. try using "send feedback" option of crash dialog and send the stack trace.

**Comment by apernouille** [comment]
I did not answer because the error seems to be fixed in the last versions. I will reopen the issue if it comes up again.
