### ISSUE TITLE
General Question about adding apps in the list

### ISSUE THREAD

**Issue by jydhthrshrhty** [j-hc/mindetach-magisk#11]
First of all thank you for this module.

i have a question, to add other apps in the list , I just need to add it to detach.txt and flip the toggle off on then reboot or i have to make the process of reinstalling and rebooting? 

🙏 thank you

**Comment by j-hc** [comment]
most simple way to add new apps:
1- add apps in the detach.txt
2- reflash the module

no need for a reboot or disabling/uninstalling module

**Comment by jydhthrshrhty** [comment]
Thank you
