### ISSUE TITLE
How to access detach.txt

### ISSUE THREAD

**Issue by KuraKuraHira** [j-hc/mindetach-magisk#12]
Hello, I understand how to add app to the list as stated in the usage sextion.

But how do I even access this detach.txt?

I don't have sdcard on my phone so I don't know where is this "/sdcard/detach.txt" is. I tried extracting the zip file, add app to the detach.txt, and compress it again but magisk don't want to extracted it.

The usage section only explain how to add app to the txt but don't give a location or guide on how to get there. 

Please help me on how to get the txt, thank you.

**Comment by j-hc** [comment]
/sdcard isnt an external sdcard. it's the internal storage, same place as where the Android or Download folders are.

**Comment by KuraKuraHira** [comment]
Hello, sorry for the late reply. I found the /sdcard folder but I'm still not sure what to do after that.

I ended up making my own solution. I use mixplorer and open the detach.txt inside the mindetach-v3,3.zip, add youtube and youtube music, save it, and install with magisk delta. This method only work with mixplorer because it has built-in text editor and doesn't need to extract the zip file before/after a change.

Altough I already resolved it I would still appreciate it if you could give a method how to do it properly, thank you.

**Comment by KuraKuraHira** [comment]
> I ended up making my own solution. I use mixplorer and open the detach.txt inside the mindetach-v3,3.zip, add youtube and youtube music, save it, and install with magisk delta. This method only work with mixplorer because it has built-in text editor and doesn't need to extract the zip file before/after a change.

Nevermind, it doesn't work. YouTube still got auto-updated. Maybe it's just me, but I really don't understand how to use this at all.

**Comment by j-hc** [comment]
read the readme https://github.com/j-hc/mindetach-magisk#usage

i dont know how else it can be explained. create /sdcard/detach.txt, put the apps in it, flash the module in magisk.

**Comment by KuraKuraHira** [comment]
Hello, I finally figure it out. So, I supposed to make a detach.txt file right in the internal storage and add the app list from there.

I think I got confused because 1). I don't know where /sdcard is; 2). Usage section implies that the detach.txt is already present. It could use some tweak to make it clearer.

And thank you for responding to all my questions.
