### ISSUE TITLE
Submit module to Magisk Modules repo

### ISSUE THREAD

**Issue by devnoname120** [j-hc/mindetach-magisk#13]
It would help discoverability by users and make the project more future-proof.

https://github.com/Magisk-Modules-Alt-Repo/submission

**Comment by j-hc** [comment]
i disagree. not needed.

**Comment by LeeBinder** [comment]
@j-hc not needed but would be helpful/ convenient. A phone or a computer aren't "needed", either - all we "need" is food, water, air, shelter .. ;)
