### ISSUE TITLE
installation failed with NO play store (aosp)

### ISSUE THREAD

**Issue by atesin** [j-hc/mindetach-magisk#15]
hi... i want to install youtube revanced extended magisk module.... but seem it doesn't work without mindetach
- phone: umidigi a5 pro (mediatek helio p23 = arm64 v8)
- android 10, rooted (havoc os + magisk)
- micro g magisk module (the "full" one, not which comes with youtube [re]vanced)
- mindetach v3.3

these are the logs from magisk module installation, it complains about cleaning play store data, but i don't have any play store to clean up (fakestore?)....  or am i doing something wrong?
```
- Copying zip to temp directory
- Installing mindetach-v3.3.zip
- Device is system-as-root
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: module.prop
***********
 mindetach 
 by j-hc 
***********
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: customize.sh
*******************
 Powered by Magisk 
*******************
- Extracting module files
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: customize.sh
  inflating: module.prop
  inflating: service.sh
  inflating: detacher-arm
  inflating: detacher-arm64
  inflating: detach.txt
- Do not clean the data of Play Store
- Open Play Store and reflash mindetach again!

! Installation failed
```

**Comment by j-hc** [comment]
the only purpose why mindetach exists is to detach apps from play store. what do you think is going to happen when you flash it with no play store?

also there are forks of my repo revanced-magisk-module that changes the module scripts with buggy ones. if you downloaded from one of them, dont report any bugs to me.

**Comment by atesin** [comment]
ok...  but take it easy and dont complaint me ..., i didnt knew it, i am just a normal user learning how to enhance his phone ...  you could put these statements clear somewhere visible to advice other users like me

anyway...  thanks for your fantastic tools

**Comment by j-hc** [comment]
i did. the description of mindetach here says:
"Simpler and better Magisk module to detach apps from Play Store"

**Comment by atesin** [comment]
sorry
