### ISSUE TITLE
v3.3 Can't flash via fox magisk module manager

### ISSUE THREAD

**Issue by sarf2k4** [j-hc/mindetach-magisk#17]
Hi, I would like to ask you that, this module can't be installed via magisk module manager, however it can be installed from magisk directly.

I am on magisk 25.1, app 26.2
magisk module manager v1.1.0
mindetach version3.3 and 2.4

Previously I had mindetach v2.4 installed via magisk module manager and there were no problem. While installing mindetach v3.3 via magisk module manager the terminal shows something similar to

```
- Do not clean the data of Play Store
- Open Play Store and reflash mindetach again!
```
I did as it asked by opening the play store, then reflash mindetach v3.3 via magisk module manager; results were the same with the error above.

**Comment by LeeBinder** [comment]
@sarf2k4 installing mindetach latest v3.3 works fine incl. correct detaching via latest [Fox's Mmm - Androidacy Module Manager](https://www.androidacy.com/downloads/?view=FoxMMM), tested with [v.2.1.1.](https://github.com/Androidacy/MagiskModuleManager/releases/tag/v2.1.1)

**Comment by sarf2k4** [comment]
Thank you @LeeBinder for the info. I was avoiding v2.0.2 as they had the flashing bugs going on. I can confirm mindetach can be flash via fmmm v2.1.1 too
