### ISSUE TITLE
Add support for commenting out packages in detach.txt and shitty to run module from terminal

### ISSUE THREAD

**Issue by james28909** [j-hc/mindetach-magisk#18]
Please add support for commenting out packages in /sdcard/detach.txt file. And also, it would be useful to be able to run this module from terminal without having to call the full path of the detacher.

Also, i downloaded the source to try to do this myself, but the source.gz actually doesn't contain the source, but does contain the already compiled module, which we can already obtain by just downloading the module. Is there any way to get you to publish the source? If so, then someone could help.

Best regards and thanks

**Comment by j-hc** [comment]
added support for commenting out with `#`

and release the source here https://github.com/j-hc/mindetach-magisk/tree/master/detacher
