### ISSUE TITLE
What's the purpose of this module?

### ISSUE THREAD

**Issue by xslvrxslwt** [j-hc/mindetach-magisk#6]
As the title says, play store already allows you to turn off auto updates for certain apps so *why*?

![Screenshot_20221102-235627_Google Play Store](https://user-images.githubusercontent.com/105242066/199617967-b50282c6-b592-4cc9-a0d2-454867708889.png)

**Comment by j-hc** [comment]
play store updates apps after some period of time ignoring that option. mindetach blocks that and also removes those apps from the update list and notifications.
