### ISSUE TITLE
Not Working on Xiaomi Mi Pad 5

### ISSUE THREAD

**Issue by xChAmeLIoNz** [j-hc/mindetach-magisk#7]
As title says.
I tried this on my tablet running arrow os 13 with magisk 25.2
I created the 'detach.txt' file in the root of internal storage. (it also created a 'detach.bak' file)
Inside the file I put these package names in the following order:

'com.google.android.youtube' (I'm using youtube revanced magisk module)
'com.spotify.music'
'com.instagram.android' (all without quotation marks)

After some time youtube revanced got updated and returned to stock youtube app.

I can provide further info if needed.

**Comment by peetezaah** [comment]
Did you try putting the file in the module's folder, re-enabling or rebooting?
Mine wasn't working either, so I did all 3 of those. I put the txt on "/data/adb/mindetach/", force-closed youtube+play store apps, re-enabled the module in magisk and then rebooted. Youtube was no longer showing the in the app updates tab.

**Comment by j-hc** [comment]
can you test this:
1. flash mindetach
2. make sure updates disappeared from play store
3. open play store and add a new account
4. check updates from the new account and see if updates returned back

**Comment by daylightdev** [comment]
Here the update apear after add a new account

**Comment by daylightdev** [comment]
Playstore keep updating YouTube.

**Comment by xChAmeLIoNz** [comment]
> can you test this:
> 
>     1. flash mindetach
> 
>     2. make sure updates disappeared from play store
> 
>     3. open play store and add a new account
> 
>     4. check updates from the new account and see if updates returned back

I'm writing this because the module stopped working again. If I try and add a new can I still use my previous account?

**Comment by andigenn** [comment]
Not working on my Mi 8 os 10 with magisk 25.2.
After some time youtube revanced got updated and returned to stock youtube app.
I have tried both of the above methods, to no avail.

**Comment by j-hc** [comment]
https://github.com/j-hc/mindetach-magisk/releases/tag/20230212

try v3

**Comment by andigenn** [comment]
Tried. YouTube is still visible in the Google play store. I attach the screenshot of the installation. Thank's for your job.
![Screenshot_2023-02-12-13-39-13-021_kpl eaah i p](https://user-images.githubusercontent.com/17638454/218312056-82e11682-c7f0-490c-a0ea-a90f4f3b37d9.jpg)

**Comment by j-hc** [comment]
> Tried. YouTube is still visible in the Google play store. I attach the screenshot of the installation. Thank's for your job. ![Screenshot_2023-02-12-13-39-13-021_kpl eaah i p](https://user-images.githubusercontent.com/17638454/218312056-82e11682-c7f0-490c-a0ea-a90f4f3b37d9.jpg)

did you force close play store and check again

**Comment by andigenn** [comment]
I forcibly closed Google play store and now it works. Thank you very much.
