### ISSUE TITLE
Constant reattachment on Pixel/LineageOS

### ISSUE THREAD

**Issue by LaeMat** [j-hc/mindetach-magisk#8]
I have a Pixel 4 running LineageOS 19. I also have the latest version of mindetach which is supposed to detach YouTube, however, it often will reattach out of the blue. I also have a OnePlus 7 Pro on OxygenOS 12, with mindetach setup the same way, and it has never detached YouTube once. 

Is there any way I could try and diagnose what is causing it to reattach?

**Comment by j-hc** [comment]
can you send the magisk flash logs from the device it cant detach?

**Comment by LaeMat** [comment]
> can you send the magisk flash logs from the device it cant detach?

I'm not sure what you mean? It installs fine and doesn't throw any errors.

**Comment by j-hc** [comment]
need to see the logs when you flash the module where this happens:

> and it has never detached YouTube once.

**Comment by LaeMat** [comment]
> need to see the logs when you flash the module where this happens:
> 
> > and it has never detached YouTube once.

Sorry, i meant to say reattached. Oxygen hasn't reattached youtube since install, but Lineage reattaches it randomly.

**Comment by j-hc** [comment]
try with v3.2

**Comment by LaeMat** [comment]
> try with v3.2

Tried flashing 3.2. says "ERROR executing query: mindetach_up"

**Comment by j-hc** [comment]
you need to start clean coming from older versions.
clean data of play store then flash

**Comment by LaeMat** [comment]
> you need to start clean coming from older versions. clean data of play store then flash

Now it says "ERROR executing query: no such table: auto_update"

**Comment by LaeMat** [comment]
> just pushed v3.3 that should fix it

Currently it's working, thanks!
