### ISSUE TITLE
On Google Play, YouTube still shows an "Update" option

### ISSUE THREAD

**Issue by xuanhung1509** [j-hc/mindetach-magisk#9]
After I flashed this module and rebooted, I checked out YouTube on Playstore and it still have `Update` option. Is this the correct behavior? 

Steps I made:
- Flash YouTube Magisk Module. Reboot.
- Create a `detach.txt` with the content of `com.google.android.youtube`.
- Flash this module (in the Magisk log, it recognized the app). Reboot.

![image](https://user-images.githubusercontent.com/89293664/224462775-b0b3c22e-3108-46a9-b38e-950a10c008a2.png)

**Comment by j-hc** [comment]
yes this is normal.
